// Place here the transaction data array. Use it in your application as needed.
export const transactions = [
  {
    id: 1,
    type: 'income',
    category: 'salary',
    amount: 3000,
    description: 'Monthly salary',
    date: '2025-11-25',
  },
  {
    id: 2,
    type: 'expense',
    category: 'groceries',
    amount: 150.5,
    description: 'Supermarket shopping',
    date: '2025-12-05',
  },
  {
    id: 3,
    type: 'expense',
    category: 'rent',
    amount: 980,
    description: 'Monthly rent',
    date: '2025-12-01',
  },
  {
    id: 4,
    type: 'income',
    category: 'freelance',
    amount: 420,
    description: 'Selling socks',
    date: '2025-12-20',
  },
  {
    id: 5,
    type: 'expense',
    category: 'utilities',
    amount: 110.25,
    description: 'Electricity and water',
    date: '2025-12-15',
  },
  {
    id: 6,
    type: 'expense',
    category: 'entertainment',
    amount: 60,
    description: 'Concert tickets',
    date: '2025-12-27',
  },
  {
    id: 7,
    type: 'income',
    category: 'investment',
    amount: 150,
    description: 'Stock market',
    date: '2025-12-10',
  },
  {
    id: 8,
    type: 'expense',
    category: 'transportation',
    amount: 45,
    description: 'Monthly bus pass',
    date: '2025-11-03',
  },
  {
    id: 9,
    type: 'expense',
    category: 'groceries',
    amount: 95,
    description: 'Weekly groceries',
    date: '2025-11-10',
  },
  {
    id: 10,
    type: 'expense',
    category: 'entertainment',
    amount: 120,
    description: 'New video game',
    date: '2025-11-20',
  },
];
